In [9]:
import os
import numpy as np
import pandas as pd

print(os.getcwd())

data = np.load("../data/highfidelity/NT_smallMCrun.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    print(f"   → {arr[:3]}")   # print first 3 elements as a preview
    print()

/home/catef/PEDS_py/my-PEDS-NT/modules
'params': shape=(100, 6), dtype=float32
   → [[0.944564   0.9526858  0.944028   0.42991555 0.64996123 0.7274391 ]
 [0.76939356 0.9946779  0.5371706  0.1515806  0.59423745 0.45688656]
 [0.34334248 0.62953085 0.3829998  0.05499905 0.7727593  0.03963903]]

'params_raw': shape=(100, 6), dtype=float32
   → [[11.556512    0.9526858  43.6007      5.4393244   0.5599845  71.82317   ]
 [10.1551485   0.9946779  33.429264    3.2126448   0.537695   63.706596  ]
 [ 6.74674     0.62953085 29.574995    2.4399924   0.60910374 51.18917   ]]

'keffs': shape=(100,), dtype=float32
   → [1.1889957 1.0211697 1.0140918]

'keff_stds': shape=(100,), dtype=float32
   → [0.00080985 0.00085994 0.00073577]

'param_names': shape=(6,), dtype=<U28
   → ['r0_b4c_rod_outer_radius' 'r0_b4c_rod_cr_fraction'
 'r1_fuel_annulus_outer_radius']

'bounds_lo': shape=(6,), dtype=float32
   → [ 4.  0. 20.]

'bounds_hi': shape=(6,), dtype=float32
   → [12.  1. 45.]



In [10]:
params = data['params']

print(f"Global min: {params.min():.6f}  (should be >= 0)")
print(f"Global max: {params.max():.6f}  (should be <= 1)")

# Turn the 6-parameter array into a readable DataFrame
df = pd.DataFrame(data['params_raw'], columns=data['param_names'])
df['keff'] = data['keffs']
df.head(10)   # renders as a formatted table in Jupyter

Global min: 0.000350  (should be >= 0)
Global max: 0.998480  (should be <= 1)


,r0_b4c_rod_outer_radius,r0_b4c_rod_cr_fraction,r1_fuel_annulus_outer_radius,r1_fuel_annulus_enrichment,r1_fuel_annulus_f_mod,r2_water_outer_radius,keff
0,11.556512,0.952686,43.600700,5.439324,0.559985,71.823174,1.188996
1,10.155149,0.994678,33.429264,3.212645,0.537695,63.706596,1.021170
2,6.746740,0.629531,29.574995,2.439992,0.609104,51.189171,1.014092
3,9.239386,0.577480,25.056202,9.240696,0.354286,71.098923,0.978032
4,5.641399,0.864329,33.659836,7.010476,0.649303,74.213715,1.253527
5,5.664272,0.771340,32.286804,3.224965,0.567302,53.980515,1.090355
6,8.588620,0.654346,40.736500,9.558659,0.451033,70.272766,1.201914
7,7.573712,0.953827,36.506981,8.634194,0.582303,53.078213,1.237903
8,9.390934,0.825741,26.414959,8.290689,0.489258,52.427223,1.036935
9,5.800577,0.575861,25.480385,6.999584,0.662079,60.387241,1.167589


In [5]:
import numpy as np
import pandas as pd

print(os.getcwd())

data = np.load("../data/highfidelity/high_fidelity_2_20000.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    print(f"   → {arr[:3]}")   # print first 3 elements as a preview
    print()

/home/catef/PEDS_py/my-PEDS-NT/modules
'pores': shape=(20000, 25), dtype=object
   → [[0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1]
 [1 0 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0]
 [1 0 1 0 0 0 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1]]

'kappas': shape=(20000,), dtype=object
   → [15.69323164819951 17.892849814343734 18.55094923272452]

