In [ ]:
import os
import numpy as np
import pandas as pd

print(os.getcwd())

data = np.load("../data/highfidelity/NT_smallMCrun.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    print(f"   → {arr[:3]}")   # print first 3 elements as a preview
    print()

/home/catef/PEDS_py/my-PEDS-NT/modules
'params': shape=(100, 6), dtype=float32
   → [[0.944564   0.9526858  0.944028   0.42991555 0.64996123 0.7274391 ]
 [0.76939356 0.9946779  0.5371706  0.1515806  0.59423745 0.45688656]
 [0.34334248 0.62953085 0.3829998  0.05499905 0.7727593  0.03963903]]

'params_raw': shape=(100, 6), dtype=float32
   → [[11.556512    0.9526858  43.6007      5.4393244   0.5599845  71.82317   ]
 [10.1551485   0.9946779  33.429264    3.2126448   0.537695   63.706596  ]
 [ 6.74674     0.62953085 29.574995    2.4399924   0.60910374 51.18917   ]]

'keffs': shape=(100,), dtype=float32
   → [1.1889957 1.0211697 1.0140918]

'keff_stds': shape=(100,), dtype=float32
   → [0.00080985 0.00085994 0.00073577]

'param_names': shape=(6,), dtype=<U28
   → ['r0_b4c_rod_outer_radius' 'r0_b4c_rod_cr_fraction'
 'r1_fuel_annulus_outer_radius']

'bounds_lo': shape=(6,), dtype=float32
   → [ 4.  0. 20.]

'bounds_hi': shape=(6,), dtype=float32
   → [12.  1. 45.]



In [2]:
data = np.load("../data/highfidelity/MCruns.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    print(f"   → {arr[:3]}")   # print first 3 elements as a preview
    print()

'params': shape=(356, 6), dtype=float32
   → [[0.9463051  0.9061278  0.75637025 0.4295236  0.4977697  0.72845143]
 [0.7705252  0.99049485 0.4300284  0.1494206  0.45485467 0.45739177]
 [0.34299192 0.2568717  0.3063675  0.05222554 0.5923412  0.03936222]]

'params_raw': shape=(356, 6), dtype=float32
   → [[11.556512    0.9053716  38.88056     5.4393244   0.49498838 71.82317   ]
 [10.1551485   0.9893558  30.743412    3.2126448   0.47827122 63.706596  ]
 [ 6.74674     0.2590617  27.659996    2.4399924   0.5318278  51.18917   ]]

'keffs': shape=(356,), dtype=float32
   → [1.1123462  0.95500016 0.970983  ]

'param_names': shape=(6,), dtype=<U28
   → ['r0_b4c_rod_outer_radius' 'r0_b4c_rod_cr_fraction'
 'r1_fuel_annulus_outer_radius']

'bounds_lo': shape=(6,), dtype=float32
   → [4.0123177e+00 3.3556621e-03 2.0020895e+01]

'bounds_hi': shape=(6,), dtype=float32
   → [11.984582   0.9988178 44.955334 ]



In [3]:
names = data["param_names"]
print("Parameter names:", names)

Parameter names: ['r0_b4c_rod_outer_radius' 'r0_b4c_rod_cr_fraction'
 'r1_fuel_annulus_outer_radius' 'r1_fuel_annulus_enrichment'
 'r1_fuel_annulus_f_mod' 'r2_water_outer_radius']


In [3]:
params = data['params']

print(f"Global min: {params.min():.6f}  (should be >= 0)")
print(f"Global max: {params.max():.6f}  (should be <= 1)")

# Turn the 6-parameter array into a readable DataFrame
df = pd.DataFrame(data['params_raw'], columns=data['param_names'])
df['keff'] = data['keffs']
df.head(10)   # renders as a formatted table in Jupyter

Global min: 0.000000  (should be >= 0)
Global max: 1.000000  (should be <= 1)


,r0_b4c_rod_outer_radius,r0_b4c_rod_cr_fraction,r1_fuel_annulus_outer_radius,r1_fuel_annulus_enrichment,r1_fuel_annulus_f_mod,r2_water_outer_radius,keff
0,11.556512,0.905372,38.880562,5.439324,0.494988,71.823174,1.112346
1,10.155149,0.989356,30.743412,3.212645,0.478271,63.706596,0.955000
2,6.746740,0.259062,27.659996,2.439992,0.531828,51.189171,0.970983
3,9.239386,0.154959,24.044960,9.240696,0.340715,71.098923,0.989303
4,5.641399,0.728658,30.927868,7.010476,0.561978,74.213715,1.180168
5,5.664272,0.542680,29.829443,3.224965,0.500477,53.980515,1.033199
6,8.588620,0.308692,36.589199,9.558659,0.413275,70.272766,1.163234
7,7.573712,0.907653,33.205585,8.634194,0.511727,53.078213,1.168308
8,9.390934,0.651482,25.131966,8.290689,0.441943,52.427223,0.997596
9,5.800577,0.151721,24.384308,6.999584,0.571559,60.387241,1.124147


In [5]:
import numpy as np
import pandas as pd

print(os.getcwd())

data = np.load("../data/highfidelity/high_fidelity_2_20000.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    print(f"   → {arr[:3]}")   # print first 3 elements as a preview
    print()

/home/catef/PEDS_py/my-PEDS-NT/modules
'pores': shape=(20000, 25), dtype=object
   → [[0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1]
 [1 0 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0]
 [1 0 1 0 0 0 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1]]

'kappas': shape=(20000,), dtype=object
   → [15.69323164819951 17.892849814343734 18.55094923272452]

